version: 0.0
os: linux

files:
  - source: /
    destination: /opt/javaapp

permissions:
  - object: /opt/javaapp
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 60
      runas: ubuntu
